### ISSUE TITLE
Modelado de Clase Venta

### ISSUE THREAD

**Issue by Matiassgg** [Matiassgg/Macowins#1]
Modele las ventas y las prendas asociadas a esa venta con una lista de `Prenda`
https://github.com/Matiassgg/Macowins/blob/60d804920d5f376c8320615b0f8e8777978cf1b1/src/main/java/Venta.java#L10

Se puede hacer tambien, una lista de elementos mas 'Genérico':
` List<Item> ventas = new ArrayList<>(); `

NO creo que fuese necesario esto ya que estamos hablando de un negocio de ropa, donde se venden prendas , no maquinaria industrial , por lo tanto, **no me convence** hacerlo mas genérico el modelado de la clase `Prenda`.

A menos que exista un cambio de contexto dentro del enunciado del ejercicio, no lo veo necesario.

**Comment by flbulgarelli** [comment]
¡Hola!

Si estás queriendo decir que `Item`  en tu ejemplo sería una interfaz que generalice a las prendas y otros productos, entonces no, no es necesario. 

¡Saludos!

**Comment by Matiassgg** [comment]
Buenas !

Genial entonces, pensaba justamente eso.
Gracias !
